name: publish

on:
  release:
    types: [created]

jobs:
  release:
    if: ${{ github.ref == 'master' }}
    runs-on: ubuntu-latest
    needs: test-build
    steps:
    - run: npm run publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
